### PR TITLE
ustream-openssl: Fix use-after-free crash in SSL session cleanup unde…

### LINKED ISSUE #19349: uhttpd keeps crashing when navigating menu options in LUCI
### Describe the bug

I have experienced frequent uhttpd crashes with LuCI navigation over the past month when using snapshot-based images.  The problem seems most noticeable when quickly navigating through different LuCI menu options in the left-hand frame. Users are unexpectedly logged out and must sign in again, though the issue may reoccur randomly. In some cases, the interface becomes completely unresponsive, and logs show that uhttpd has crashed.

```
Tue Jul  8 07:37:58 2025 daemon.info procd: Instance uhttpd::instance1 s in a crash loop 8 crashes, 298 seconds since last crash

```

### OpenWrt version

r30302-bce0ad5563

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Linksys MX4300

### Image kind

Official downloaded image

### Steps to reproduce

_No response_

### Actual behaviour

_No response_

### Expected behaviour

_No response_

### Additional info

_No response_

### Diffconfig

```text

```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by hauke**
…r high load

The __ustream_ssl_session_free() function was attempting to access a BIO object after it had been freed by SSL_free(). This caused segmentation faults under high load with many parallel requests.

SSL_free() automatically frees all BIOs owned by the SSL object, including any custom BIOs set via SSL_set_bio(). The code was incorrectly:
1. Calling SSL_free(us->ssl) which frees the BIO
2. Then calling BIO_get_data(bio) on the now-invalid BIO pointer

This violates OpenSSL's ownership model and leads to use-after-free memory access.

The fix moves the BIO context extraction before SSL_free(), ensuring the BIO is still valid when accessing its application data. This allows proper cleanup of the custom BIO method and context structures before the BIO itself is freed.

Fixes crash with backtrace:
  0x0000ffff81296d08 in BIO_get_data () from libcrypto.so.3
  __ustream_ssl_session_free () at ustream-openssl.c:259
  ustream_ssl_free () at ustream-ssl.c:175
  ustream_free () at libubox/ustream.c:97

This bug was fixed with help of AI after providing the stacktrace.

Fixes: https://github.com/openwrt/openwrt/issues/19349
Fixes: https://github.com/openwrt/openwrt/issues/20134
Fixes: 5896991e46a3 ("ustream-openssl: fix BIO_method memory leak")

### CODE REVIEW

**Comment by hauke** [comment]
I found it like this:
Running OpenWrt in qemu with port forwarding, you can also use a normal device:
```
./scripts/qemustart armsr armv8 -m 512M --netdev user,id=lan,net=192.168.1.0/24,dhcpstart=192.168.1.100,restrict=yes,hostfwd=tcp::8022-192.168.1.1:22,hostfwd=tcp::8443-192.168.1.1:443,hostfwd=tcp::8080-192.168.1.1:80,hostfwd=tcp::2000-192.168.1.1:2000  --netdev user,id=wan  -net nic,netdev=lan -net nic,netdev=wan
```

attach to the running uhttpd process with gdb:
```
gdbserver --attach 0.0.0.0:2000 $(pidof /usr/sbin/uhttpd)
```
2000 is a port I use for this remote gdb session.

In my OpenWrt build I connected to the remote gdb:
```
[hauke@hauke-p14s openwrt]$ ./scripts/remote-gdb localhost:2000 staging_dir/target-aarch64_generic_musl/root-armsr/usr/sbin/uhttpd 
Using target aarch64_generic (musl, )
GNU gdb (GDB) 16.3
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-pc-linux-gnu --target=aarch64-openwrt-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from staging_dir//target-aarch64_generic_musl/root-armsr/usr/sbin/uhttpd...
__cp_end () at src/thread/aarch64/syscall_cp.s:30
30		ret
(gdb) bt
#0  __cp_end () at src/thread/aarch64/syscall_cp.s:30
#1  0x0000ffff8175139c in __syscall_cp_c (nr=22, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=<optimized out>) at src/thread/pthread_cancel.c:33
#2  0x0000ffff8170fe04 in epoll_pwait (fd=<optimized out>, ev=ev@entry=0xffff816ee328 <events>, cnt=cnt@entry=10, to=<optimized out>, sigs=sigs@entry=0x0) at src/linux/epoll.c:28
#3  0x0000ffff8170fe24 in epoll_wait (fd=<optimized out>, ev=ev@entry=0xffff816ee328 <events>, cnt=cnt@entry=10, to=<optimized out>) at src/linux/epoll.c:37
#4  0x0000ffff816d4640 in uloop_fetch_events (timeout=<optimized out>) at /home/hauke/openwrt/openwrt/build_dir/target-aarch64_generic_musl/libubox-2026.02.13~1aa36ee7/uloop-epoll.c:72
#5  uloop_run_events (timeout=<optimized out>) at /home/hauke/openwrt/openwrt/build_dir/target-aarch64_generic_musl/libubox-2026.02.13~1aa36ee7/uloop.c:199
#6  uloop_run_timeout (timeout=-1) at /home/hauke/openwrt/openwrt/build_dir/target-aarch64_generic_musl/libubox-2026.02.13~1aa36ee7/uloop.c:679
#7  0x0000aaaae64f2f88 in ?? ()
#8  0x0000ffffe4c81408 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) c
Continuing.
```
Let it run with `c`.

I ran the script from https://github.com/openwrt/openwrt/issues/20134#issuecomment-3827262175 to reproduce the problem. 

suddenly gdb detected a `SIGSEGV` and I asked for the backtrace `bt`
```
Program received signal SIGSEGV, Segmentation fault.
0x0000ffff81296d08 in BIO_get_data () from /home/hauke/openwrt/openwrt/scripts/../staging_dir/target-aarch64_generic_musl/root-armsr/usr/lib/libcrypto.so.3
(gdb) bt
#0  0x0000ffff81296d08 in BIO_get_data () from /home/hauke/openwrt/openwrt/scripts/../staging_dir/target-aarch64_generic_musl/root-armsr/usr/lib/libcrypto.so.3
#1  0x0000ffff8160b8c8 in __ustream_ssl_session_free (us=us@entry=0xffff80e97508) at /home/hauke/openwrt/openwrt/build_dir/target-aarch64_generic_musl/ustream-ssl-openssl/ustream-ssl-2025.10.03~5a81c108/ustream-openssl.c:259
#2  0x0000ffff8160ac40 in ustream_ssl_free (s=0xffff80e97508) at /home/hauke/openwrt/openwrt/build_dir/target-aarch64_generic_musl/ustream-ssl-openssl/ustream-ssl-2025.10.03~5a81c108/ustream-ssl.c:175
#3  0x0000ffff816d5950 in ustream_free (s=0xffff80e97508) at /home/hauke/openwrt/openwrt/build_dir/target-aarch64_generic_musl/libubox-2026.02.13~1aa36ee7/ustream.c:97
#4  0x0000aaaae64f4ab0 in ?? ()
#5  0x0000ffff80e97578 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) info threads 
  Id   Target Id                 Frame 
* 1    Thread 2512.2512 "uhttpd" 0x0000ffff81296d08 in BIO_get_data () from /home/hauke/openwrt/openwrt/scripts/../staging_dir/target-aarch64_generic_musl/root-armsr/usr/lib/libcrypto.so.3
(gdb)
```

I opened github copilot, gave it the trace and asked to explain and fix the bug. Later I also asked it fgor a commit description. 

After the first fix I ran into this error
```
Program received signal SIGSEGV, Segmentation fault.
0x0000ffffa0f04cec in BIO_free () from /home/hauke/openwrt/openwrt/scripts/../staging_dir/target-aarch64_generic_musl/root-armsr/usr/lib/libcrypto.so.3
(gdb) bt
#0  0x0000ffffa0f04cec in BIO_free () from /home/hauke/openwrt/openwrt/scripts/../staging_dir/target-aarch64_generic_musl/root-armsr/usr/lib/libcrypto.so.3
#1  0x0000ffffa0f05eb4 in BIO_free_all () from /home/hauke/openwrt/openwrt/scripts/../staging_dir/target-aarch64_generic_musl/root-armsr/usr/lib/libcrypto.so.3
#2  0x0000ffffa0dcedb4 in ossl_ssl_connection_free () from /home/hauke/openwrt/openwrt/scripts/../staging_dir/target-aarch64_generic_musl/root-armsr/usr/lib/libssl.so.3
#3  0x0000ffffa0dcdf94 in SSL_free () from /home/hauke/openwrt/openwrt/scripts/../staging_dir/target-aarch64_generic_musl/root-armsr/usr/lib/libssl.so.3
#4  0x0000ffffa12798fc in __ustream_ssl_session_free (us=<optimized out>) at /home/hauke/openwrt/openwrt/build_dir/target-aarch64_generic_musl/ustream-ssl-openssl/ustream-ssl-2025.10.03~5a81c108/ustream-openssl.c:263
#5  0x0000ffffa1278c40 in ustream_ssl_free (s=0xffffa09837e8) at /home/hauke/openwrt/openwrt/build_dir/target-aarch64_generic_musl/ustream-ssl-openssl/ustream-ssl-2025.10.03~5a81c108/ustream-ssl.c:175
#6  0x0000ffffa1343950 in ustream_free (s=0xffffa09837e8) at /home/hauke/openwrt/openwrt/build_dir/target-aarch64_generic_musl/libubox-2026.02.13~1aa36ee7/ustream.c:97
#7  0x0000aaaaabee4ab0 in ?? ()
#8  0x0000ffffa0983858 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) 
``` 
AI also fixed that with some help.

**Comment by brada4** [comment]
Kind of affects 32bit too....

> AI also

OMG

**Comment by hauke** [comment]
> Kind of affects 32bit too....
> 
> > AI also
> 
> OMG

I do not understand this comment.

File: ustream-io-openssl.c [hunk 1]
```diff
@@ -116,22 +122,32 @@ static long s_ustream_ctrl(BIO *b, int cmd, long num, void *ptr)
...
+	BIO_meth_set_create(meth, s_ustream_new);
+	BIO_meth_set_destroy(meth, s_ustream_free);
+
+	return meth;
+}
+
 static BIO *ustream_bio_new(struct ustream *s)
 {
 	BIO *bio;
 	struct bio_ctx *ctx = calloc(1, sizeof(struct bio_ctx));
```
Comment (ynezz) [inline ustream-io-openssl.c]: While at it, can we handle this possible allocation failure?

File: ustream-io-openssl.c [hunk 2]
```diff
@@ -116,22 +122,32 @@ static long s_ustream_ctrl(BIO *b, int cmd, long num, void *ptr)
 	};
 }
 
+static BIO_METHOD *ustream_meth(void)
+{
+	static BIO_METHOD *meth = NULL;
```
Comment (ynezz) [inline ustream-io-openssl.c:127]: Since you're making this singleton, shouldn't the `meth` field be removed from the struct https://github.com/openwrt/ustream-ssl/blob/5a81c108d20e24724ed847cc4be033f2a74e6635/ustream-openssl.h#L39-L42 ?

**Review by ynezz — APPROVED** [review]
Thanks, LGTM, just a small remarks.

**Comment by brada4** [comment]
Kind of still crashes in same spot.

File: ustream-io-openssl.c (hunk 2 above)
Comment (hauke) [reply ustream-io-openssl.c:127]: Fixed, I think the AI also mad this change and I forgot to copy it.

File: ustream-io-openssl.c (hunk 1 above)
Comment (hauke) [reply ustream-io-openssl.c]: added some handling, but it is not very well handled.

**Comment by hauke** [comment]
> Kind of still crashes in same spot.

It works for me in Firefox and Chromium and with the script from the bug report.

If you still see this problem, please connect gdb to the uhttpd and post the backtrace.
